__title__ = 'healtheintent-api-python'
__description__ = "A simple API wrapper to help us perform commonly required actions in Cerner's various HealthEIntent REST APIs."
__url__ = 'https://bitbucket.org/rkhleics/healtheintent-api-python/'
__version__ = '1.2'
__stable_version__ = '1.2'
__author__ = 'Andy Babic'
__author_email__ = 'andyjbabic@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Andy Babic'
